### ISSUE TITLE
Ch 4, table 4

### ISSUE THREAD

**Issue by CSkovhus** [OpenPEPPOL/peppol-bis-invoice-3#8] opened 2017-10-04 11:52 UTC
R57:
Suggest to make AccountingSupplierParty/PartyIdentification/ID mandatory to have at least one identification of the sender (and not only a name)

**Comment by SiwMeckelborg** [comment] 2017-12-14 13:25
Closed as this is partially a duplicate of issue #11

**Closed by SiwMeckelborg** 2017-12-14 13:25 UTC
Labels: For discussion in WG
