### ISSUE TITLE
Ch 6.2.9, Text type

### ISSUE THREAD

**Issue by CSkovhus** [OpenPEPPOL/peppol-bis-invoice-3#36] opened 2017-12-19 10:30 UTC
"And any line breaks should be preserved and respected by the receiver’s system." 
To my knowledge preserving whitespaces is not standard XML behaviour - so I think it should be the senders responsible to wrap the text in CDATA-tags if the want the whitespaces preserved.

**Comment by klakegg** [comment] 2017-12-19 22:20
Duplicate of #34. Could we limit discussions related to line breaks in the original issue to make sure all attending parties may contribute?

**Comment by CSkovhus** [comment] 2017-12-20 12:11
If you reopen the issue, I will copy my comment and close this issue - as far as I can tell I'm not able to reopen it.

**Closed** 2017-12-20 12:14 UTC
